version: '3.7'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/web
      - ./web:/web
    depends_on:
      - clickhouse
    environment:
      - GIN_MODE=release
      - PORT=5000
      - SECRET_KEY=token
      - EXPIRATION_TIME=10
      - DATABASE=file::memory:?cache=shared
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_HTTP_PORT=8123
      - CLICKHOUSE_TCP_PORT=9000
